// plugins/anime.ts
import {
  Animatable,
  Draggable,
  JSAnimation,
  Scope,
  ScrollObserver,
  Spring,
  Timeline,
  Timer,
  WAAPIAnimation,
  animate,
  createAnimatable,
  createDraggable,
  createScope,
  createSpring,
  createTimeline,
  createTimer,
  eases,
  engine,
  onScroll,
  scrollContainers,
  stagger,
  svg,
  utils,
  waapi,
} from "animejs";
export default defineNuxtPlugin(() => {
  return {
    provide: {
      Animatable,
      Draggable,
      JSAnimation,
      Scope,
      ScrollObserver,
      Spring,
      Timeline,
      Timer,
      WAAPIAnimation,
      animate,
      createAnimatable,
      createDraggable,
      createScope,
      createSpring,
      createTimeline,
      createTimer,
      eases,
      engine,
      onScroll,
      scrollContainers,
      stagger,
      svg,
      utils,
      waapi,
    },
  };
});
